num_repeat_times: 3
distribution: "dirichlet" # "iid", "non-balanced" or "dirichlet"
alpha: 0.1

server:
  global_rounds: 50
  lowest_join_rate: 0.6

client:
  num_clients: 20
  num_classes_per_client: 2
  batch_size: 64
  local_epochs: 2
  learning_rate: 0.01
